### ISSUE TITLE
Composite type definition is missing.

### ISSUE THREAD

**Issue by ninad-d** [Hydrawisk793/kurento-client-js-types#1]
Hey,

It seems that Composite type definition is missing from your typings. I do see Dispatcher, DispatcherOneToMany but do not see Composite type.

**Comment by Hydrawisk793** [comment]
@ninad-d Hi, thanks for pointing that out.
As you can see, this typings is still in work in progress and lacks many other type definitions. (e.g. filters)
So, please be careful if you want to use this on your project.
I will add missing ones as soon as i get some free time.

**Comment by Hydrawisk793** [comment]
Type declarations for `Composite` class has been added in commit a455dc66bdee721344bd59bd4c96ce4c1a1f10cb.
Closing.
